name: Multi Platform Build

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:

          # ü™ü Windows
          - os: windows-latest
            cmd: npx electron-builder --win --x64
            artifact: windows-x64
            path: dist/app/*x64.*

          - os: windows-latest
            cmd: npx electron-builder --win --ia32
            artifact: windows-x32
            path: dist/app/*ia32.*

          # üêß Linux
          - os: ubuntu-latest
            cmd: npx electron-builder --linux deb --x64
            artifact: linux-deb-x64
            path: dist/app/*x64.deb

          - os: ubuntu-latest
            cmd: npx electron-builder --linux rpm --x64
            artifact: linux-rpm-x64
            path: dist/app/*x64.rpm

          # üçé macOS
          - os: macos-15
            cmd: npx electron-builder --mac --x64
            artifact: macos-intel
            path: dist/app/*x64.*

          - os: macos-15
            cmd: npx electron-builder --mac --arm64
            artifact: macos-arm
            path: dist/app/*arm64.*

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 25

      - run: npm install --omit=optional
      - run: ${{ matrix.cmd }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.path }}
