name: Release mSearch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (ex: 26.7.0)"
        required: true
        type: string

      prerelease:
        description: "Pre-release"
        required: true
        type: boolean

      notes:
        description: "Notes de version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          git tag v${{ inputs.version }}
          git push origin v${{ inputs.version }}

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: mSearch v${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}
          body: ${{ inputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
